import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * What `seed.ts` provisions and every scenario reads back. Regenerated by
 * `pnpm loadtest:seed` - never hand-edited, never committed (see
 * `.gitignore`), since the API key/password/JWT in it are throwaway
 * dev-database credentials but still real credentials.
 */
export interface LoadtestFixture {
  apiBaseUrl: string;
  merchantId: string;
  apiKeyPlaintext: string;
  userId: string;
  email: string;
  password: string;
  /** Pre-signed `gw_access` JWT (JwtAuthGuard is stateless, so login does not need to run per scenario invocation). */
  accessToken: string;
  network: string;
  asset: string;
  currency: string;
  /** Payment addresses seeded AVAILABLE for `invoice-creation` to consume - one invoice permanently retires one address (SPEC section 8: never reuse). */
  seededAddressCount: number;
  /** Invoices created during seeding, already PENDING, for `public-invoice-polling` to read repeatedly without consuming the address pool. */
  pollInvoiceIds: string[];
}

const FIXTURE_PATH = path.join(dirname, 'fixture.json');

export function writeFixture(fixture: LoadtestFixture): void {
  writeFileSync(FIXTURE_PATH, JSON.stringify(fixture, null, 2), 'utf8');
}

export function readFixture(): LoadtestFixture {
  try {
    return JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as LoadtestFixture;
  } catch {
    throw new Error(
      `no loadtest fixture at ${FIXTURE_PATH} - run "pnpm loadtest:seed" first (with the API server already running).`,
    );
  }
}
