#!/usr/bin/env bash
# Generates infrastructure/kubernetes/secret.yaml (gitignored) with freshly
# random JWT/encryption secrets and a random Postgres password, from
# infrastructure/kubernetes/secret.example.yaml's shape. Never commit the
# output - see infrastructure/kubernetes/secret.example.yaml's own header for
# why this is a baseline (single Secret, env-var seam) rather than a real
# KMS/Vault integration, which is Phase 11 scope.
#
# Usage: scripts/kubernetes/generate-secret.sh
set -euo pipefail

cd "$(dirname "$0")/../.."

OUT=infrastructure/kubernetes/secret.yaml

rand_b64() { node -e "console.log(require('crypto').randomBytes($1).toString('base64url'))"; }
rand_pw() { node -e "console.log(require('crypto').randomBytes(24).toString('base64url'))"; }

JWT_ACCESS_SECRET=$(rand_b64 48)
JWT_REFRESH_SECRET=$(rand_b64 48)
ENCRYPTION_KEY=$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))")
POSTGRES_PASSWORD=$(rand_pw)
GATEWAY_APP_DB_PASSWORD=$(rand_pw)

cat > "$OUT" <<EOF
# Generated by scripts/kubernetes/generate-secret.sh - do not commit.
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: gateway
type: Opaque
stringData:
  POSTGRES_USER: "gateway"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_DB: "gateway"
  # api/worker/monitor connect as the least-privilege \`gateway_app\` role
  # (Phase 17 pass 1, ADR 0031) - CRUD only, no DDL, no superuser.
  # \`infrastructure/kubernetes/migration-job.yaml\` provisions this role via
  # \`pnpm db:provision-app-role\` (packages/database/prisma/provision-app-role.ts)
  # every time it runs, using DATABASE_MIGRATE_URL below.
  DATABASE_URL: "postgresql://gateway_app:${GATEWAY_APP_DB_PASSWORD}@postgres:5432/gateway?schema=public&connection_limit=20&pool_timeout=10"
  GATEWAY_APP_DB_PASSWORD: "${GATEWAY_APP_DB_PASSWORD}"
  # Superuser connection - migrations and role provisioning only. Never
  # injected into api/worker/monitor; only migration-job.yaml uses it.
  DATABASE_MIGRATE_URL: "postgresql://gateway:${POSTGRES_PASSWORD}@postgres:5432/gateway?schema=public&connection_limit=20&pool_timeout=10"
  REDIS_URL: "redis://redis:6379"
  JWT_ACCESS_SECRET: "${JWT_ACCESS_SECRET}"
  JWT_REFRESH_SECRET: "${JWT_REFRESH_SECRET}"
  ENCRYPTION_KEY: "${ENCRYPTION_KEY}"
  ENCRYPTION_KEY_ID: "k8s-baseline-1"
  COINGECKO_API_KEY: ""
  ETHEREUM_RPC_URL: ""
  ETHEREUM_RPC_WS_URL: ""
  ETHEREUM_RPC_FALLBACK_URL: ""
  POLYGON_RPC_URL: ""
  POLYGON_RPC_WS_URL: ""
  POLYGON_RPC_FALLBACK_URL: ""
  BSC_RPC_URL: ""
  BSC_RPC_WS_URL: ""
  BSC_RPC_FALLBACK_URL: ""
  BITCOIN_RPC_URL: ""
  BITCOIN_RPC_USER: ""
  BITCOIN_RPC_PASSWORD: ""
  ETHEREUM_SEPOLIA_RPC_URL: ""
  POLYGON_AMOY_RPC_URL: ""
  BSC_TESTNET_RPC_URL: ""
  BITCOIN_TESTNET_RPC_URL: ""
  SIGNING_SERVICE_URL: ""
  SIGNING_SERVICE_TOKEN: ""
  KMS_KEY_ID: ""
  COMPLIANCE_API_KEY: ""
EOF

echo "Wrote $OUT (gitignored - apply with: kubectl apply -f $OUT)"
